# Changes here will be overwritten by Copier
_commit: c485062
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: rust
add_wiki: false
email: prettygoodcapital@gmail.com
github: prettygoodcapital
project_description: Standard financial dates
project_name: finance dates
python_version_primary: '3.11'
team: PrettyGoodCapital
